### PR TITLE
Update lemonldap-ng-pg to support external DB init

### PR DESCRIPTION
**Pull request by ducnm0711**

### CODE REVIEW

**Comment by guimard** [comment]
Hi @ducnm0711 , if we use this container for initialize an external db, maybe it should then exit(0) instead of launching its db ?

**Comment by ducnm0711** [comment]
> Hi @ducnm0711 , if we use this container for initialize an external db, maybe it should then exit(0) instead of launching its db ?

Yes indeed. Shoul signal container to stop after successful init.

**Comment by ducnm0711** [comment]
Update README to instruct override the container Entrypoint. Guide for k8s mode will be in separate helm chart contribution PR.

**Comment by ducnm0711** [comment]
Hi @guimard it's tested and can be merge whenever you ready

**Comment by guimard** [comment]
Fixed in a89d7fc + 470adec

Tag 2.19.0-2

**Pull request merged**
